namespace:
  name: staging

image:
  repository: nginx
  tag: 1.18.0

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi

service:
  type: ClusterIP
  port: 8111

configmap:
  data: "version: 1.18.0"